import streamlit as st, os, sys
sys.path.insert(0, os.path.dirname(__file__))
from utils import CSS, render_sidebar, init_state, html

st.set_page_config(page_title="World Development Dashboard", page_icon="🌍", layout="wide", initial_sidebar_state="expanded")
st.markdown(CSS, unsafe_allow_html=True)
init_state(); render_sidebar()

html('<div style="text-align:center;padding:3.5rem 1rem 2rem;"><div style="font-size:3.5rem;margin-bottom:1rem;">🌍</div><div style="font-size:2.75rem;font-weight:900;background:linear-gradient(135deg,#60A5FA,#818CF8,#5EEAD4);-webkit-background-clip:text;-webkit-text-fill-color:transparent;letter-spacing:-.5px;line-height:1.15;">World Development Dashboard</div><div style="font-size:1.05rem;color:#94A3B8;margin-top:.9rem;max-width:780px;margin-left:auto;margin-right:auto;line-height:1.75;">Explore, analyze, and discover hidden patterns in how countries develop over time — economically, socially, politically, technologically, and environmentally.</div><div style="font-size:.86rem;color:#64748B;margin-top:1rem;">Powered by data mining techniques: clustering, PCA, Apriori rules, anomaly detection, and time series analysis.</div></div>')

cards=[('📦','Build World Data','Build a dataset either live from the World Bank API or from the included local CSV. Choose countries, years, regions, and real indicators.','START HERE','#7C3AED'),('📥','Import Data','Upload CSV, Excel, or JSON. The app inspects messy structure, missingness, types, duplicates, and readiness.','OPTIONAL','#2563EB'),('🧹','Prepare Data','Run a full preprocessing pipeline: duplicates, numeric conversion, missing values, outliers, skew, low variance, categorical encoding, and scaling.','REQUIRED','#059669'),('🧩','Country Similarity','Use K-Means, DBSCAN, and Hierarchical clustering to discover groups of similar countries and explain similarity with actual numbers.','MANDATORY','#D97706'),('🗺️','Development Map','Use PCA to produce 2D/3D development maps, scree plots, cumulative variance, loadings, and biplots.','MANDATORY','#0891B2'),('🔗','Pattern Rules','Use Apriori association rules to find a manageable set of meaningful development relationships.','OPTIONAL','#9333EA'),('📈','Trends Over Time','Analyze country time series: trend, differencing, stationarity, ACF/PACF, ARIMA, residuals, RMSE/MAPE, and forecasts.','OPTIONAL','#0EA5E9'),('🚨','Unusual Countries','Run Isolation Forest, LOF, and consensus detection with interpretation of why each country is unusual.','OPTIONAL','#DC2626')]

out='<div style="display:grid;grid-template-columns:repeat(auto-fit,minmax(285px,1fr));gap:1.1rem;max-width:1180px;margin:0 auto 2.5rem;">'
for icon,title,desc,badge,color in cards:
    out += f'<div style="background:#12172A;border:1px solid #263149;border-radius:18px;padding:1.45rem 1.55rem;border-top:4px solid {color};box-shadow:0 12px 30px rgba(0,0,0,.18);min-height:220px;"><div style="font-size:1.9rem;margin-bottom:.8rem;">{icon}</div><div style="font-size:1.05rem;font-weight:850;color:#F8FAFC;margin-bottom:.55rem;">{title}</div><div style="font-size:.88rem;color:#94A3B8;line-height:1.65;">{desc}</div><div style="margin-top:1rem;font-size:.72rem;color:{color};font-weight:850;letter-spacing:.08em;text-transform:uppercase;">{badge}</div></div>'
out+='</div>'
html(out)
html('<div style="max-width:1180px;margin:0 auto 2.2rem;background:#0F172A;border:1px solid #263149;border-radius:18px;padding:1.35rem 1.6rem;"><div style="font-size:1rem;font-weight:850;color:#F8FAFC;margin-bottom:.6rem;">🎯 Project Goal</div><div style="font-size:.9rem;color:#94A3B8;line-height:1.75;">This system is not just a chart gallery. It helps users understand <b style="color:#CBD5E1;">why countries are similar</b>, <b style="color:#CBD5E1;">which indicators explain differences</b>, and <b style="color:#CBD5E1;">how development patterns change over time</b>.</div></div>')
html('<div style="text-align:center;color:#64748B;font-size:.82rem;padding:1rem 0 2rem;">An-Najah National University · Data Mining 10672349<br>Bilal Anabosi · Yaqoob Hanbali · Mohammad Sayeh</div>')
